const alaskan = {
  title: 'ALASKAN',
  image: 'public/assets/img/starters/alaskan.jpg',
  discount: '$12.99',
  price: '$7.19',
  description: `There are 2 san francisco starters mixed into the BEAST, along with 8 of our other starters!!!

WHO DOES THIS? WE DO!!!

SO: MAD MAX, THUNDER DOME...LOOK IT UP....TWO MEN ENTER , ONE MAN LEAVES!!!
THE BEAST AKA THE BASTARD: WHAT IS IT , WHO IS IT?
WE HAVE 10 VERY DIFFERENT STARTERS, s.f. SALLY, LARRY, s.f. BELLA, SAMMY, SHASHA, WALT, THE ALASKAN, GRANNY Z, BIG JOHN AND IVANASKI....YEAH YEAH, YOU CAN ONLY GET THE FIRST 4 HERE ON EBAY...TOO BAD.....
BUT: NOW WHAT HAPPENS WHEN YOU THROW THEM ALL INTO "THUNDER DOME"? WHO WILL TEAM UP, WHO WILL SLEEP TOGETHER AND REPRODUCE, WHO WILL KILL, WHO WILL SURVIVE?
SO MANY QUESTIONS....AND WHY DID WE DO THIS IN THE FIRST PLACE? WHY NOT?
THE RESULT AFTER OVER 5 YEARS OF BEING ADDED INTO, YEAH EVERY TIME WE INCREASE OUR SUPPLIES OF OUR STARTERS, A LITTLE OF THAT STARTER GOES INTO THE CAGE MATCH...
SO BASICALLY, THE BASTARD CHANGES ALL THE TIME AND IS NEVER THE SAME....BWAHAHAHAHA...
THIS IS TRUELY A CRAZY STARTER, FAST ACTING, EATS ANYTHING, GROWS CONSTANTLY OUT OF ITS SPACE, BIG GAS PRODUCER.....WHAT ELSE CAN WE SAY, JUST DON'T LET IT GET LOOSE, IT MIGHT EAT YOUR DOG!!!`,
};

export default alaskan;
